package cn.vo.controller.hans;

import java.util.HashMap;
import java.util.Map;

public class EnumerationMap {

    public static Integer getFraction(String que){
        Map<String,Integer> map = new HashMap();
        map.put("th1",2);
        map.put("th2",2);
        map.put("th3",1);
        map.put("th4",2);
        map.put("th5",1);
        map.put("th6",1);
        map.put("th7",1);
        map.put("th8",1);
        map.put("th9",1);
        map.put("th10",1);
        map.put("th11",1);
        map.put("th12",2);
        map.put("th13",1);
        map.put("th14",1);
        map.put("th15",1);
        map.put("th16",3);
        map.put("th17",3);
        map.put("th18",3);
        map.put("th19",3);
        map.put("th20",3);
        map.put("th21",2);
        map.put("th22",2);
        map.put("th23",2);
        map.put("th24",1);
        map.put("th25",1);
        map.put("th26",1);
        map.put("th27",1);
        map.put("th28",1);
        map.put("th29",2);
        map.put("th30",1);
        map.put("th31",1);
        map.put("th32",2);
        map.put("th33",2);
        map.put("th34",2);
        map.put("th35",2);
        map.put("th36",2);
        map.put("th37",2);
        map.put("th38",1);
        map.put("th39",2);
        map.put("th40",2);
        map.put("th41",2);
        map.put("th42",2);
        map.put("th43",2);
        map.put("th44",2);
        map.put("th45",2);
        map.put("th46",2);
        map.put("th47",2);
        map.put("th48",2);
        map.put("th49",2);
        map.put("th50",2);
        map.put("th51",1);
        map.put("th52",2);
        map.put("th53",1);
        map.put("th54",1);
        map.put("th55",1);
        map.put("th56",1);
        map.put("th57",1);
        map.put("th58",2);
        map.put("th59",1);
        map.put("th60",1);
        map.put("th61",2);
        return map.get(que);
    }

    public static Integer getSift(String que){
        Map<String,Integer> map = new HashMap();
        map.put("th1",4);
        map.put("th2",4);
        map.put("th4",4);
        map.put("th5",2);
        map.put("th6",4);
        map.put("th7",4);
        map.put("th8",2);
        map.put("th9",2);
        map.put("th10",4);
        map.put("th11",4);
        map.put("th12",2);
        map.put("th13",2);
        map.put("th14",2);
        map.put("th15",4);
        map.put("th16",4);
        map.put("th17",4);
        map.put("th18",4);
        map.put("th19",2);
        map.put("th20",4);
        map.put("th21",2);
        map.put("th22",4);
        map.put("th23",4);
        map.put("th24",4);
        map.put("th25",4);
        map.put("th26",4);
        map.put("th27",4);
        map.put("th28",4);
        map.put("th29",4);
        map.put("th30",2);
        map.put("th31",2);
        return map.get(que);
    }

    public static Integer getRed(String que){
        Map<String,Integer> map = new HashMap();
        map.put("th1",1);
        map.put("th2",1);
        map.put("th3",1);
        map.put("th4",2);
        map.put("th5",2);
        map.put("th6",1);
        map.put("th7",1);
        map.put("th8",1);
        map.put("th9",2);
        map.put("th10",2);
        map.put("th11",1);
        map.put("th12",2);
        map.put("th13",3);
        map.put("th14",1);
        map.put("th15",2);
        map.put("th16",1);
        map.put("th17",1);
        map.put("th18",1);
        map.put("th19",1);
        map.put("th20",1);
        map.put("th21",2);
        map.put("th22",1);
        map.put("th23",1);
        map.put("th24",1);
        map.put("th25",1);
        map.put("th26",2);
        map.put("th27",2);
        map.put("th28",1);
        map.put("th29",2);
        map.put("th30",1);
        map.put("th31",2);
        map.put("th32",2);
        map.put("th33",2);
        map.put("th34",2);
        map.put("th35",3);
        map.put("th36",2);
        map.put("th37",2);
        map.put("th38",2);
        map.put("th39",3);
        map.put("th40",3);
        map.put("th41",5);
        map.put("th42",3);
        map.put("th43",3);
        map.put("th44",2);
        map.put("th45",4);
        map.put("th46",3);
        map.put("th47",2);
        map.put("th48",3);
        map.put("th49",2);
        map.put("th50",3);
        map.put("th51",3);
        map.put("th52",2);
        return map.get(que);
    }


}
