server:
   port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.145.251:3306/product?characterEncoding=utf-8&useSSL=false
    username: root
    password: yiYIAA%6hjIJ
  thymeleaf:
    prefix: classpath:/templates/
    cache: false  # 此处为不缓存页面
 
mybatis:
  mapper-locations: classpath:cn/vo/mapping/*.xml
  type-aliases-package: cn.vo.pojo
